name: "abbreviation_generation_POC"

data:
    train: "data/train"
    dev:  "data/dev"
    test: "data/test"
    dataset_type: "plain"
    src:
        lang: "src"
        max_length: 100
        min_length: 1
        level: "word"
        voc_limit: 400
        voc_min_freq: 1
        voc_file: "data/vocab.txt"
    
    trg:
        lang: "tgt"
        max_length: 100
        min_length: 1
        level: "word"
        voc_limit: 400
        voc_min_freq: 1
        voc_file: "data/vocab.txt"
    
testing:
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 10
    batch_type: "sentence"
    eval_metrics: ["token_accuracy"]
    max_output_length: 100
    return_prob: "none"

training:
    #random_seed: 42
    optimizer: "adam"
    learning_rate: 0.01
    learning_rate_min: 0.0001
    clip_grad_norm: 1.0
    weight_decay: 0.
    batch_size: 100
    batch_type: "sentence"
    normalization: "batch"
    scheduling: "plateau"
    patience: 10
    decrease_factor: 0.5
    epochs: 1000
    validation_freq: 100
    logging_freq: 100
    early_stopping_metric: "acc"
    model_dir: "copy-model"
    overwrite: True #Only set True when debugging
    shuffle: True
    use_cuda: False
    print_valid_sents: [0, 3, 6]
    keep_best_chpts: 1
    fp16: True

model:
    initializer: "xavier_uniform"
    init_weight: 0.01
    init_gain: 1.0
    bias_initializer: "zeros"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    embed_init_gain: 1.0
    init_rnn_orthogonal: False
    lstm_forget_gate: 1.
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "recurrent"
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 128
            scale: False
            freeze: False
            #load_pretrained: No pretrained embeddings exist
        hidden_size: 64
        bidirectional: True
        dropout: 0.2
        num_layers: 1
        freeze: False
    decoder:
        type: "recurrent"
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 128
            scale: False
            freeze: False
            #load_pretrained: No pretrained embeddings exist
        hidden_size: 128
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 1
        input_feeding: True
        init_hidden: "last"
        attention: "bahdanau"
        freese: False